### ISSUE TITLE
[BUG] Airport and DVDs not able to play on MacMini2,1

### ISSUE THREAD

**Issue by alexknop** [rmc-team/osx-patcher#17]
**Describe the bug**
I installed El Capitan successfully on my Mac Mini2,1 but Airport is not recognized and the DVD Drive isn't fully functional. The DVD drive recognizes a disk and I can open the drive to view files, but DVD Player app is not recognizing it. (I have tested this DVD and disk drive on my other partition of 10.7 and it is working)

**To Reproduce**
For Airport:
Go to System Preferences > Network. Airport is missing. It is also not an option when you click the +

For DVDs:
Try to play a DVD on the disk drive and the DVD Player application will give you an Initialization Error "A valid video device could not be found for playback. [-70017]"

**Screenshots/logs**
If applicable, add screenshots and/or logs to help explain your problem.

**Mac (please complete the following information):**
 - OS: mac OS 10.11
 - MacMini 2,1 (Mid-2007, 2Ghz Intel Core 2 Duo)

**Additional context**
Let me know if you guys need anything that may help.

**Comment by julian-fairfax** [comment]
Hi,
I think the AirPort issue is known cause @parrotgeek1 couldn't get it working with his patcher either. I haven't heard of the DVD issue though and unfortunately I don't have a Macmini myself to test it on so there's not too much I can. If you have another Mac you could try to see if DVD sharing works?

**Comment by parrotgeek1** [comment]
The DVD player issue is because of the partial graphics acceleration. It
works fine in 32-bit 10.8.

The Wi-Fi issue is because the macmini2,1 (and *only* the macmini2,1) uses
a different wifi card for which support got removed from 10.8+. It's
possible to get it to work fairly well in 10.8.x but not in anything newer
(the drivers load but the airport menu is broken because the drivers are
too old for the rest of the frameworks, and the frameworks are too old to
swap out).

FYI, the issue with my patcher is that WiFi doesn't work on macmini2,1
before you install the drivers package, meaning you need ethernet to do the
security updates. Once the package is installed, it works.

**Comment by julian-fairfax** [comment]
Thanks for your explanation. I suppose Wi-Fi would work on 10.8 then so I'd recommend that, but I'm not sure. You're better off using parrotgeek1's patcher if you're running 10.8 anyway though.

**Comment by parrotgeek1** [comment]
WiFi would not work on *your* 10.8 because (iirc) you're not replacing the
WiFi drivers from 10.8DP1, which still had airportatheros21 support.
Anyway, that's beside the point.

**Comment by julian-fairfax** [comment]
Oh yeah probably not then.

**Comment by alexknop** [comment]
Thank you guys for the input.


Alex Knop

(248) 802-0782


________________________________
